fn_call_width = 110
fn_args_layout = "Compressed"

# function_arguments = "Visual"

overflow_delimited_expr = true

remove_nested_parens = true

reorder_imports = true

use_small_heuristics = "Max"

chain_width = 110
max_width = 115
